[v1]
"cargo-credential-pass 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-credential-pass"]
"ikconfig 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["ikconfig"]
