[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[[keyboard.bindings]]
key = "с"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "м"
mods = "Control|Shift"
action = "Paste"
